name: snaake
description: Snaake is a small and very simple clone of the classic snake game from Nokia phones.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.27.0
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.6
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/food/
    - assets/images/snake/
